# Generated by Django 4.2.5 on 2023-11-26 20:36

from django.db import migrations, models
from inventario.models import Inventario

def create_inventario(apps, schema_editor):

    # Crear el primer artículo de inventario
    articulo1_computadora = Inventario.objects.create(
        codigo="100001",
        articulo='Articulo 1',
        marca='Marca 1',
        modelo='Modelo 1',
        no_serie='Serie 1',
        descripcion='Esta es una descripción del artículo 1.',
        cantidad=10,
        costo=1000,
        categoria='COM'  # Computadora
    )
    articulo1_computadora.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('articulo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('no_serie', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo', models.IntegerField()),
                ('categoria', models.CharField(choices=[('COM', 'Computadora'), ('TEL', 'Telefono'), ('ASE', 'Asesorios'), ('RPC', 'Repuestos de Computadoras'), ('RPT', 'Repuestos de Telefonos')], max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_inventario),
    ]
