# Generated by Django 4.2.5 on 2023-12-09 02:15

from django.db import migrations, models
from inventario.models import Inventario

def create_inventario(apps, schema_editor):

    # Crear el primer artículo de inventario
    articulo1_computadora = Inventario.objects.create(
        codigo="C00001",
        articulo='Articulo 1',
        marca='Marca 1',
        modelo='Modelo 1',
        no_serie='Serie 1',
        descripcion='Esta es una descripción del artículo 1.',
        cantidad=10,
        costo=1000,
        categoria='COM',  # Computadora
        is_active=True,
    )
    articulo1_computadora.save()

    articulo2_computadora = Inventario.objects.create(
        codigo="C00002",
        articulo='Articulo 2',
        marca='Marca 2',
        modelo='Modelo 2',
        no_serie='Serie 2',
        descripcion='Esta es una descripción del artículo 2.',
        cantidad=10,
        costo=1000,
        categoria='COM',  # Computadora
        is_active=True,
    )
    articulo2_computadora.save()

    articulo3_computadora = Inventario.objects.create(
        codigo="C00003",
        articulo='Articulo 3',
        marca='Marca 3',
        modelo='Modelo 3',
        no_serie='Serie 3',
        descripcion='Esta es una descripción del artículo 3.',
        cantidad=10,
        costo=1000,
        categoria='COM',  # Computadora
        is_active=True,
    )
    articulo3_computadora.save()

    articulo4_computadora = Inventario.objects.create(
        codigo="C00004",
        articulo='Articulo 4',
        marca='Marca 4',
        modelo='Modelo 4',
        no_serie='Serie 4',
        descripcion='Esta es una descripción del artículo 4.',
        cantidad=10,
        costo=1000,
        categoria='COM',  # Computadora
        is_active=True,
    )
    articulo4_computadora.save()

    articulo5_computadora = Inventario.objects.create(
        codigo="C00005",
        articulo='Articulo 5',
        marca='Marca 5',
        modelo='Modelo 5',
        no_serie='Serie 5',
        descripcion='Esta es una descripción del artículo 5.',
        cantidad=10,
        costo=1000,
        categoria='COM',  # Computadora
        is_active=True,
    )
    articulo5_computadora.save()

    articulo6_computadora = Inventario.objects.create(
        codigo="C00006",
        articulo='Articulo 6',
        marca='Marca 6',
        modelo='Modelo 6',
        no_serie='Serie 6',
        descripcion='Esta es una descripción del artículo 6.',
        cantidad=10,
        costo=1000,
        categoria='COM',  # Computadora
        is_active=True,
    )
    articulo6_computadora.save()

    articulo7_computadora = Inventario.objects.create(
        codigo="C00007",
        articulo='Articulo 7',
        marca='Marca 7',
        modelo='Modelo 7',
        no_serie='Serie 7',
        descripcion='Esta es una descripción del artículo 7.',
        cantidad=10,
        costo=1000,
        categoria='COM',  # Computadora
        is_active=True,
    )
    articulo7_computadora.save()

    articulo1_telefono = Inventario.objects.create(
        codigo="T00001",
        articulo='Articulo 1',
        marca='Marca 1',
        modelo='Modelo 1',
        no_serie='Serie 1',
        descripcion='Esta es una descripción del artículo 1.',
        cantidad=20,
        costo=2000,
        categoria='TEL',  # Telefono
        is_active=True,
    )
    articulo1_telefono.save()

    articulo2_telefono = Inventario.objects.create(
        codigo="T00002",
        articulo='Articulo 2',
        marca='Marca 2',
        modelo='Modelo 2',
        no_serie='Serie 2',
        descripcion='Esta es una descripción del artículo 2.',
        cantidad=20,
        costo=2000,
        categoria='TEL',  # Telefono
        is_active=True,
    )
    articulo2_telefono.save()

    articulo3_telefono = Inventario.objects.create(
        codigo="T00003",
        articulo='Articulo 3',
        marca='Marca 3',
        modelo='Modelo 3',
        no_serie='Serie 3',
        descripcion='Esta es una descripción del artículo 3.',
        cantidad=20,
        costo=2000,
        categoria='TEL',  # Telefono
        is_active=True,
    )
    articulo3_telefono.save()

    articulo4_telefono = Inventario.objects.create(
        codigo="T00004",
        articulo='Articulo 4',
        marca='Marca 4',
        modelo='Modelo 4',
        no_serie='Serie 4',
        descripcion='Esta es una descripción del artículo 4.',
        cantidad=20,
        costo=2000,
        categoria='TEL',  # Telefono
        is_active=True,
    )
    articulo4_telefono.save()

    articulo5_telefono = Inventario.objects.create(
        codigo="T00005",
        articulo='Articulo 5',
        marca='Marca 5',
        modelo='Modelo 5',
        no_serie='Serie 5',
        descripcion='Esta es una descripción del artículo 5.',
        cantidad=20,
        costo=2000,
        categoria='TEL',  # Telefono
        is_active=True,
    )
    articulo5_telefono.save()

    articulo6_telefono = Inventario.objects.create(
        codigo="T00006",
        articulo='Articulo 6',
        marca='Marca 6',
        modelo='Modelo 6',
        no_serie='Serie 6',
        descripcion='Esta es una descripción del artículo 6.',
        cantidad=20,
        costo=2000,
        categoria='TEL',  # Telefono
        is_active=True,
    )
    articulo6_telefono.save()

    articulo7_telefono = Inventario.objects.create(
        codigo="T00007",
        articulo='Articulo 7',
        marca='Marca 7',
        modelo='Modelo 7',
        no_serie='Serie 7',
        descripcion='Esta es una descripción del artículo 7.',
        cantidad=20,
        costo=2000,
        categoria='TEL',  # Telefono
        is_active=True,
    )
    articulo7_telefono.save()

    articulo1_accesorio = Inventario.objects.create(
        codigo="A00001",
        articulo='Articulo 1',
        marca='Marca 1',
        modelo='Modelo 1',
        no_serie='Serie 1',
        descripcion='Esta es una descripción del artículo 1.',
        cantidad=20,
        costo=2000,
        categoria='ASE',  # Acessorio
        is_active=True,
    )
    articulo1_accesorio.save()

    articulo2_accesorio = Inventario.objects.create(
        codigo="A00002",
        articulo='Articulo 2',
        marca='Marca 2',
        modelo='Modelo 2',
        no_serie='Serie 2',
        descripcion='Esta es una descripción del artículo 2.',
        cantidad=20,
        costo=2000,
        categoria='ASE',  # Acessorio
        is_active=True,
    )
    articulo2_accesorio.save()

    articulo3_accesorio = Inventario.objects.create(
        codigo="A00003",
        articulo='Articulo 3',
        marca='Marca 3',
        modelo='Modelo 3',
        no_serie='Serie 3',
        descripcion='Esta es una descripción del artículo 3.',
        cantidad=20,
        costo=2000,
        categoria='ASE',  # Acessorio
        is_active=True,
    )
    articulo3_accesorio.save()

    articulo4_accesorio = Inventario.objects.create(
        codigo="A00004",
        articulo='Articulo 4',
        marca='Marca 4',
        modelo='Modelo 4',
        no_serie='Serie 4',
        descripcion='Esta es una descripción del artículo 4.',
        cantidad=20,
        costo=2000,
        categoria='ASE',  # Acessorio
        is_active=True,
    )
    articulo4_accesorio.save()

    articulo5_accesorio = Inventario.objects.create(
        codigo="A00005",
        articulo='Articulo 5',
        marca='Marca 5',
        modelo='Modelo 5',
        no_serie='Serie 5',
        descripcion='Esta es una descripción del artículo 5.',
        cantidad=20,
        costo=2000,
        categoria='ASE',  # Acessorio
        is_active=True,
    )
    articulo5_accesorio.save()

    articulo6_accesorio = Inventario.objects.create(
        codigo="A00006",
        articulo='Articulo 6',
        marca='Marca 6',
        modelo='Modelo 6',
        no_serie='Serie 6',
        descripcion='Esta es una descripción del artículo 6.',
        cantidad=20,
        costo=2000,
        categoria='ASE',  # Acessorio
        is_active=True,
    )
    articulo1_accesorio.save()

    articulo7_accesorio = Inventario.objects.create(
        codigo="A00007",
        articulo='Articulo 7',
        marca='Marca 7',
        modelo='Modelo 7',
        no_serie='Serie 7',
        descripcion='Esta es una descripción del artículo 7.',
        cantidad=20,
        costo=2000,
        categoria='ASE',  # Acessorio
        is_active=True,
    )
    articulo7_accesorio.save()

    articulo1_rcp = Inventario.objects.create(
        codigo="R00001",
        articulo='Articulo 1',
        marca='Marca 1',
        modelo='Modelo 1',
        no_serie='Serie 1',
        descripcion='Esta es una descripción del artículo 1.',
        cantidad=20,
        costo=2000,
        categoria='RPC',  # Repuestos de Computadoras
        is_active=True,
    )
    articulo1_rcp.save()

    articulo2_rcp = Inventario.objects.create(
        codigo="R00002",
        articulo='Articulo 2',
        marca='Marca 2',
        modelo='Modelo 2',
        no_serie='Serie 2',
        descripcion='Esta es una descripción del artículo 2.',
        cantidad=20,
        costo=2000,
        categoria='RPC',  # Repuestos de Computadoras
        is_active=True,
    )
    articulo2_rcp.save()

    articulo3_rcp = Inventario.objects.create(
        codigo="R00003",
        articulo='Articulo 3',
        marca='Marca 3',
        modelo='Modelo 3',
        no_serie='Serie 3',
        descripcion='Esta es una descripción del artículo 3.',
        cantidad=20,
        costo=2000,
        categoria='RPC',  # Repuestos de Computadoras
        is_active=True,
    )
    articulo3_rcp.save()

    articulo4_rcp = Inventario.objects.create(
        codigo="R00004",
        articulo='Articulo 4',
        marca='Marca 4',
        modelo='Modelo 4',
        no_serie='Serie 4',
        descripcion='Esta es una descripción del artículo 4.',
        cantidad=20,
        costo=2000,
        categoria='RPC',  # Repuestos de Computadoras
        is_active=True,
    )
    articulo4_rcp.save()

    articulo5_rcp = Inventario.objects.create(
        codigo="R00005",
        articulo='Articulo 5',
        marca='Marca 5',
        modelo='Modelo 5',
        no_serie='Serie 5',
        descripcion='Esta es una descripción del artículo 5.',
        cantidad=20,
        costo=2000,
        categoria='RPC',  # Repuestos de Computadoras
        is_active=True,
    )
    articulo5_rcp.save()

    articulo6_rcp = Inventario.objects.create(
        codigo="R00006",
        articulo='Articulo 6',
        marca='Marca 6',
        modelo='Modelo 6',
        no_serie='Serie 6',
        descripcion='Esta es una descripción del artículo 6.',
        cantidad=20,
        costo=2000,
        categoria='RPC',  # Repuestos de Computadoras
        is_active=True,
    )
    articulo6_rcp.save()

    articulo7_rcp = Inventario.objects.create(
        codigo="R00007",
        articulo='Articulo 7',
        marca='Marca 7',
        modelo='Modelo 7',
        no_serie='Serie 7',
        descripcion='Esta es una descripción del artículo 7.',
        cantidad=20,
        costo=2000,
        categoria='RPC',  # Repuestos de Computadoras
        is_active=True,
    )
    articulo7_rcp.save()

    articulo1_rpt = Inventario.objects.create(
        codigo="P00001",
        articulo='Articulo 1',
        marca='Marca 1',
        modelo='Modelo 1',
        no_serie='Serie 1',
        descripcion='Esta es una descripción del artículo 1.',
        cantidad=20,
        costo=2000,
        categoria='RPT',  # Repuestos de Telefonos
        is_active=True,
    )
    articulo1_rpt.save()

    articulo2_rpt = Inventario.objects.create(
        codigo="P00002",
        articulo='Articulo 2',
        marca='Marca 2',
        modelo='Modelo 2',
        no_serie='Serie 2',
        descripcion='Esta es una descripción del artículo 2.',
        cantidad=20,
        costo=2000,
        categoria='RPT',  # Repuestos de Telefonos
        is_active=True,
    )
    articulo2_rpt.save()

    articulo3_rpt = Inventario.objects.create(
        codigo="P00003",
        articulo='Articulo 3',
        marca='Marca 3',
        modelo='Modelo 3',
        no_serie='Serie 3',
        descripcion='Esta es una descripción del artículo 3.',
        cantidad=20,
        costo=2000,
        categoria='RPT',  # Repuestos de Telefonos
        is_active=True,
    )
    articulo3_rpt.save()

    articulo4_rpt = Inventario.objects.create(
        codigo="P00004",
        articulo='Articulo 4',
        marca='Marca 4',
        modelo='Modelo 4',
        no_serie='Serie 4',
        descripcion='Esta es una descripción del artículo 4.',
        cantidad=20,
        costo=2000,
        categoria='RPT',  # Repuestos de Telefonos
        is_active=True,
    )
    articulo4_rpt.save()

    articulo5_rpt = Inventario.objects.create(
        codigo="P00005",
        articulo='Articulo 5',
        marca='Marca 5',
        modelo='Modelo 5',
        no_serie='Serie 5',
        descripcion='Esta es una descripción del artículo 5.',
        cantidad=20,
        costo=2000,
        categoria='RPT',  # Repuestos de Telefonos
        is_active=True,
    )
    articulo5_rpt.save()

    articulo6_rpt = Inventario.objects.create(
        codigo="P00006",
        articulo='Articulo 6',
        marca='Marca 6',
        modelo='Modelo 6',
        no_serie='Serie 6',
        descripcion='Esta es una descripción del artículo 6.',
        cantidad=20,
        costo=2000,
        categoria='RPT',  # Repuestos de Telefonos
        is_active=True,
    )
    articulo6_rpt.save()

    articulo7_rpt = Inventario.objects.create(
        codigo="P00007",
        articulo='Articulo 7',
        marca='Marca 7',
        modelo='Modelo 7',
        no_serie='Serie 7',
        descripcion='Esta es una descripción del artículo 7.',
        cantidad=20,
        costo=2000,
        categoria='RPT',  # Repuestos de Telefonos
        is_active=True,
    )
    articulo7_rpt.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('articulo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('no_serie', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo', models.IntegerField()),
                ('categoria', models.CharField(choices=[('COM', 'Computadora'), ('TEL', 'Telefono'), ('ASE', 'Asesorios'), ('RPC', 'Repuestos de Computadoras'), ('RPT', 'Repuestos de Telefonos')], max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.RunPython(create_inventario)
    ]
