# Generated by Django 4.2.5 on 2024-01-15 15:28

from django.db import migrations, models
from configuracion.models import Impuesto

def create_impuesto(apps, schema_editor):

    articulo1_computadora = Impuesto.objects.create(
        iva="IVA 6%",
        valor=0.16,
    )
    articulo1_computadora.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_impuesto)
    ]
