# Generated by Django 5.0.1 on 2024-02-26 14:45

from django.db import migrations, models
from configuracion.models import Dolar

def create_dolar(apps, schema_editor):

    moneda = Dolar.objects.create(
        moneda="Dolar",
        valor=0.0,
    )
    moneda.save()


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_dolar)
    ]
